baseURL = "http://example.org/"
languageCode = "en-us"
title = "Title of hugo toml"

[params]
includeListPagesInTaxonomyLists = false

[taxonomies]
person="persons"
society="societies"
group="groups"

[markup.goldmark.renderer]
  unsafe = true
